Repository drink-this/drink-this-frontend, pull requests merged in 2021-08, with the labels that each got.

#22 Taija.landing page refactor
  .DS_Store
  public/.DS_Store
  public/images/drew_beamer_on_unsplash_friends_cheers.png
  src/.DS_Store
  src/actions/auth_actions/confirm_login_action.js
  src/components/app.js
  src/components/auth_panel.js
  src/components/landing.js
  src/components/logged_in_app.js
  src/components/logged_out_app.js
  src/components/onboard.js
  src/components/sign_in_button.js
  src/components/white_logo.js
  src/images/.DS_Store
  src/images/drew_beamer_on_unsplash_friends_cheers.png
  src/images/zoomed-drink-this-landing.jpg
  src/test/Landing.test.js
  tailwind.config.js
Labels: Frontend, Refactor Job, help wanted

#29 Landing page
  src/actions/auth_actions/confirm_login_action.js
  src/actions/example_store_actions/get_example_message.js
  src/components/app.js
  src/components/auth_panel.js
  src/components/authenticated_route.js
  src/components/header.js
  src/components/onboard.js
  src/components/search.js
  src/components/search_results.js
  src/components/sign_in_button.js
  src/components/social_links.js
  src/components/unauthenticated_route.js
  src/config/routes.js
  src/constants.js
  src/core/app_actions.js
  src/core/router.js
  src/stores/auth_store.js
  src/test/app_actions.test.js
  src/test/router.test.js
Labels: Frontend, Refactor Job, enhancement

#30 Style changes to landing page
  src/components/landing.js
  src/components/white_logo.js
Labels: Frontend, enhancement

#37 Add yelp button to show page
  package-lock.json
  package.json
  src/actions/auth_actions/confirm_login_action.js
  src/components/cocktail.js
  src/components/show_page.js
  src/components/stars.js
Labels: Frontend, enhancement

#38 Send ratings
  src/components/auth_panel.js
  src/components/cocktail.js
  src/components/show_page.js
  src/components/sign_in_button.js
  src/components/star.js
  src/components/stars.js
Labels: Frontend, enhancement

#43 Add sign out button
  src/actions/action_repo.js
  src/actions/auth_actions/logout_action.js
  src/components/app.js
  src/components/authenticated_route.js
  src/components/header.js
  src/components/sign_out_button.js
  src/constants.js
  src/stores/auth_store.js
Labels: Frontend, enhancement

#41 Yelp search
  src/__mocks__/cocktails.js
  src/components/cocktail.js
  src/components/search.js
  src/components/search_results.js
  src/components/show_page.js
  src/components/yelp_search.js
  src/service/cocktail.js
  src/test/search_results.test.js
  src/test/yelp_search.test.js
  tailwind.config.js
Labels: Frontend, enhancement

#62 Add readme
  README.md
Labels: documentation, Backend

#66 Spell our names correctly
  README.md
Labels: Frontend

#67 Update README.md
  README.md
Labels: Frontend

#68 Update README.md
  README.md
Labels: Frontend

#77 Refactor frontend
  src/actions/action_repo.js
  src/actions/auth_actions/confirm_login_action.js
  src/actions/auth_actions/logout_action.js
  src/actions/example_store_actions/get_example_message.js
  src/actions/get_cocktail_actions/get_cocktail_action.js
  src/actions/get_cocktail_actions/get_cocktails_action.js
  src/actions/onboard_actions/get_drinks_action.js
  src/components/app.js
  src/components/auth_panel.js
  src/components/auth_provider.js
  src/components/authenticated_route.js
  src/components/cocktail.js
  src/components/dashboard.js
  src/components/google_sign_in.js
  src/components/google_sign_out.js
  src/components/header.js
  src/components/landing.js
  src/components/logged_in_app.js
  src/components/logged_out_app.js
  src/components/logo.js
  src/components/onboard.js
  src/components/recommendation_button.js
  src/components/search.js
  src/components/search_results.js
  src/components/show_page.js
  src/components/sign_in_button.js
  src/components/sign_out_button.js
  src/components/stars.js
  src/components/starter_cocktails.js
  src/components/unauthenticated_route.js
  src/components/yelp_search.js
  src/config/routes.js
  src/constants.js
  src/service/cocktail.js
  src/stores/auth_mall.js
  src/stores/auth_store.js
  src/stores/cocktail_store.js
  src/stores/example_store.js
  src/stores/google_auth_store.js
  src/stores/onboard_store.js
  src/test/google_sign_in.test.js
  src/test/landing.test.js
  src/test/logo.test.js
  src/test/onboard.test.js
  src/test/search_results.test.js
  src/test/show_page.test.js
Labels: Frontend, Refactor Job

#81 Age check
  .DS_Store
  src/.DS_Store
  src/components/landing.js
  src/components/modal.js
  src/images/.DS_Store
  src/images/bernard-hermant-1nDW7BjBj1s-unsplash.jpg
  src/stores/age_confirm_store.js
  src/test/landing.test.js
  tailwind.config.js
Labels: enhancement, Frontend

#85 Refactor modal
  src/components/age_verification_modal.js
  src/components/landing.js
Labels: Frontend, Refactor Job

#86 Add spinners
  .babelrc
  package-lock.json
  package.json
  src/actions/auth_actions/confirm_login_action.js
  src/actions/get_cocktail_actions/get_cocktail_action.js
  src/actions/get_cocktail_actions/get_cocktails_action.js
  src/actions/homepage_actions/get_info.js
  src/actions/onboard_actions/get_drinks_action.js
  src/components/app.js
  src/components/cocktail.js
  src/components/google_sign_in.js
  src/components/loading_spinner.js
  src/components/show_page.js
  src/stores/cocktail_store.js
  src/stores/google_auth_store.js
  src/stores/homepage_store.js
  src/stores/onboard_store.js
  src/stores/spinner_store.js
Labels: enhancement, Frontend

#84 Second auth refactor
  src/actions/auth_actions/confirm_login_action.js
  src/actions/auth_actions/logout_action.js
  src/components/google_sign_in.js
  src/components/landing.js
  src/components/onboard.js
  src/components/show_page.js
  src/constants.js
  src/stores/auth_mall.js
  src/stores/google_auth_store.js
  src/test/onboard.test.js
Labels: Frontend, Refactor Job

#90 Hotfix authentication
  src/components/landing.js
  src/components/show_page.js
  src/stores/auth_mall.js
Labels: bug, Frontend
