Repository drink-this/drink-this-frontend, pull requests merged in 2021-07, with the labels that each got.

#19 Update DTR.md
  DTR.md
Labels: Backend, Frontend

#14 Create search
  src/components/app.js
  src/components/header.js
Labels: Core, Frontend

#18 Add circleci config
  .circleci/config.yml
  Procfile
  package-lock.json
  package.json
  public/index.html
  tailwind.config.js
Labels: Frontend
